version: "2"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/:cached
            - ./docker/site.conf:/etc/nginx/conf.d/site.conf
            - ./docker/ca.crt:/etc/nginx/keys/ca.crt
            - ./docker/ca.key:/etc/nginx/keys/ca.key
        links:
            - php
    php:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                - user=${USER}
        volumes:
            - ./:/var/www/html/:cached
        user: ${USER}
        links:
          - dockerdb
          - mailhog
    dockerdb:
        image: mariadb:latest
        volumes:
          - "./.data/db/data:/var/lib/mysql"
        environment:
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=docker
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        ports:
          - "3306:3306"

    mailhog:
          image: mailhog/mailhog
          ports:
            - "8025:8025"
            - "1025:1025"