<?php

namespace AppBundle\Repository;

/**
 * TimelogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimelogRepository extends \Doctrine\ORM\EntityRepository
{
}
